-- Sample data for suppliers table
INSERT INTO suppliers (
  name,
  description,
  category,
  sustainability_score,
  location,
  certifications,
  contact_email,
  website,
  established_year,
  employee_count,
  carbon_footprint,
  renewable_energy_percentage,
  waste_recycling_rate,
  water_usage_efficiency,
  supply_chain_transparency,
  verified
) VALUES
(
  'EcoMaterials Inc.',
  'Leading manufacturer of recycled plastic materials for construction and packaging industries.',
  'Manufacturing',
  95,
  'Portland, OR',
  '{"ISO 14001", "Carbon Neutral Certified", "FSC Certified"}',
  'contact@ecomaterials.com',
  'https://ecomaterials.com',
  2010,
  150,
  1250.50,
  85.5,
  92.3,
  'Excellent',
  'High',
  true
),
(
  'GreenTech Solutions',
  'Sustainable electronics manufacturer specializing in energy-efficient devices and recycled components.',
  'Electronics',
  88,
  'Austin, TX',
  '{"ISO 14001", "Energy Star Partner", "EPEAT Gold"}',
  'info@greentech-solutions.com',
  'https://greentech-solutions.com',
  2015,
  75,
  890.25,
  78.2,
  87.1,
  'Good',
  'High',
  true
),
(
  'BioFiber Textiles',
  'Organic cotton and bamboo fiber textile producer committed to fair trade and sustainable farming.',
  'Textiles',
  92,
  'Asheville, NC',
  '{"GOTS Certified", "Fair Trade Certified", "Organic Content Standard"}',
  'sales@biofiber-textiles.com',
  'https://biofiber-textiles.com',
  2008,
  200,
  1450.75,
  95.0,
  94.8,
  'Excellent',
  'High',
  true
),
(
  'SolarPack Packaging',
  'Biodegradable packaging solutions made from renewable plant-based materials.',
  'Packaging',
  90,
  'Denver, CO',
  '{"ASTM D6400", "OK Compost Certified", "ISO 14001"}',
  'hello@solarpack.com',
  'https://solarpack.com',
  2012,
  95,
  675.30,
  82.1,
  89.5,
  'Good',
  'Medium',
  true
),
(
  'AquaPure Water Systems',
  'Water purification and recycling systems for industrial and municipal applications.',
  'Water Treatment',
  87,
  'Seattle, WA',
  '{"NSF Certified", "ISO 14001", "WaterSense Partner"}',
  'support@aqua-pure.com',
  'https://aqua-pure.com',
  2009,
  120,
  980.45,
  76.8,
  85.2,
  'Good',
  'High',
  true
),
(
  'ForestGuard Timber',
  'Sustainable timber harvesting and processing with reforestation commitments.',
  'Forestry',
  85,
  'Portland, ME',
  '{"FSC Certified", "SFI Certified", "ISO 14001"}',
  'operations@forestguard.com',
  'https://forestguard.com',
  1998,
  180,
  2100.80,
  70.5,
  78.9,
  'Average',
  'High',
  true
),
(
  'CleanEnergy Motors',
  'Electric vehicle components manufacturer using recycled rare earth materials.',
  'Automotive',
  89,
  'Detroit, MI',
  '{"ISO 14001", "IATF 16949", "Energy Star Partner"}',
  'business@cleanenergy-motors.com',
  'https://cleanenergy-motors.com',
  2018,
  85,
  1120.60,
  88.7,
  91.4,
  'Good',
  'Medium',
  true
),
(
  'GreenHarvest Organics',
  'Organic food processing and packaging facility serving regional farmers markets.',
  'Food Processing',
  91,
  'Madison, WI',
  '{"USDA Organic", "Non-GMO Verified", "ISO 22000"}',
  'orders@greenharvest-organics.com',
  'https://greenharvest-organics.com',
  2011,
  65,
  540.25,
  92.3,
  96.7,
  'Excellent',
  'High',
  true
);